### ISSUE TITLE
How to call Extbase Controllers?

### ISSUE THREAD

**Issue by simonschaufi** [sinso/app_routes#12]
It would be great if I could also call extbase controllers and not just controllers which implement the required interface.

**Comment by smichaelsen** [comment]
Hey @simonschaufi, that's currently not supported out of the box. You'd need an intermediate layer which bootstraps extbase, creates an extbase request, calls the controller and then wrap the result into a PSR-7 response.

At the moment it's unlikely for me to provide this as I have no use case, but a PR would be welcome.

**Comment by georgringer** [comment]
I would really drop that issue - you could then just use a json response in the controller but this ext should be kind of alternative to previous eIDs

calling extbase repositories is still possible (Which is IMO also bit code smell)

**Comment by simonschaufi** [comment]
I don't use this extension at the moment but was considering using it for an API. If my customer really needs it, I might look for an alternative or code something with this one but for now I'll close it.
